version: '3'
services:
  foxgirlsorg-manga:
    container_name: foxgirlsorg-manga
    build: .
    image: foxgirlsorg-manga:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: foxgirlsorg-mangaDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - foxgirlsorg-manga
    depends_on:
      - foxgirlsorg-mangaDB
      
  foxgirlsorg-mangaDB:
    container_name: foxgirlsorg-mangaDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: mariadb:latest
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - foxgirlsorg-manga-data:/var/lib/mysql
      - ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - '3306:3306'
    networks:
      - foxgirlsorg-manga
      
 # foxgirlsorg-mangaAdminer:
  #  container_name: foxgirlsorg-mangaAdminer
   # image: adminer
   # restart: unless-stopped
   # ports:
   #   - '1338:8080'
   # environment:
   #   - ADMINER_DEFAULT_SERVER=foxgirlsorg-mangaDB
   # networks:
   #   - foxgirlsorg-manga
   # depends_on:
   #   - foxgirlsorg-mangaDB

volumes:
  foxgirlsorg-manga-data:

networks:
  foxgirlsorg-manga:
    name: Foxgirlsorg-manga
    driver: bridge
